name: Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["locoworks/home"]
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TRIGGER }}" \
          https://api.github.com/repos/${{ matrix.repo }}/dispatches \
          -d '{"event_type":"deploy"}'
